import { ARCHETYPES, type ArchetypeKey } from '../lib/archetypes'
import { useEffect, useState } from 'react'
import { useAuth } from '../hooks/useAuth'
import Toast from '../components/Toast'
import { useParams, useNavigate } from 'react-router-dom'
import { supabase } from '../lib/supabase'
import type { Block, BlockType } from '../lib/supabase'
import { BLOCK_META } from '../lib/supabase'
import BlockCard from '../components/BlockCard'

const ALL_STAGES: BlockType[] = ['hook', 'script', 'shoot', 'edit', 'publish']

const STAGE_LABELS: Record<BlockType, string> = {
  hook: 'Hook',
  script: 'Script',
  shoot: 'Shoot Plan',
  edit: 'Edit Notes',
  publish: 'Publish Strategy',
}

const STAGE_ICONS: Record<BlockType, string> = {
  hook: '🎣',
  script: '📝',
  shoot: '🎬',
  edit: '✂️',
  publish: '🚀',
}

export default function WorkflowPage() {
  const { id } = useParams<{ id: string }>()
  const navigate = useNavigate()

  const [workflowName, setWorkflowName] = useState('')
  const [editingTitle, setEditingTitle] = useState(false)
  const [blocks, setBlocks] = useState<Record<BlockType, Block | null>>({
    hook: null, script: null, shoot: null, edit: null, publish: null,
  })
  const [topic, setTopic] = useState('')
  const [platform, setPlatform] = useState<'instagram' | 'youtube' | 'linkedin'>('instagram')
  const [archetype, setArchetype] = useState<ArchetypeKey>('viral-hook')
  const [toast, setToast] = useState<{ message: string; type: 'success' | 'error' } | null>(null)
  const [generating, setGenerating] = useState(false)
  const [isExportOpen, setIsExportOpen] = useState(false)

  const { user } = useAuth()
  const isPro = user?.user_metadata?.is_pro === true || localStorage.getItem('cre8flow_pro') === 'true'
  const showToast = (message: string, type: 'success' | 'error') => setToast({ message, type })

  const handleExportOption = (type: 'md' | 'pdf') => {
    setIsExportOpen(false)
    if (type === 'md') handleMarkdownExport()
    else handlePDFExport()
  }

  const generateMarkdown = () => {
    let content = `# ${workflowName}\nGenerated by Cre8Flow | ${new Date().toISOString().slice(0, 10)}\n\n`
    ALL_STAGES.forEach((type) => {
      const block = blocks[type]
      if (!block) return
      content += `## ${block.title}\n`
      if (block.notes) content += `${block.notes}\n---\n`
    })
    return content
  }

  const handleMarkdownExport = () => {
    const content = generateMarkdown()
    const blob = new Blob([content], { type: 'text/plain;charset=utf-8' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `${workflowName.replace(/\s+/g, '-')}-cre8flow.md`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }

  const handlePDFExport = () => {
    document.body.classList.add('printing')
    window.print()
    setTimeout(() => document.body.classList.remove('printing'), 500)
  }

  const handleTitleSave = async () => {
    if (!id) return
    try {
      await supabase.from('workflows').update({ name: workflowName }).eq('id', id)
      setEditingTitle(false)
      showToast('Workflow name saved', 'success')
    } catch (e) {
      console.error(e)
      showToast('Failed to save workflow name', 'error')
    }
  }

  useEffect(() => {
    if (!id) return
    const load = async () => {
      const { data: wf } = await supabase.from('workflows').select('*').eq('id', id).single()
      if (wf) setWorkflowName(wf.name)

      const { data: blks } = await supabase.from('blocks').select('*').eq('workflow_id', id).order('order_index')
      if (blks) {
        const map: Record<BlockType, Block | null> = { hook: null, script: null, shoot: null, edit: null, publish: null }
        blks.forEach((b) => { map[b.type as BlockType] = b })
        setBlocks(map)
      }
    }
    load()
  }, [id])

  const handleGenerate = async () => {
    if (!topic.trim()) return
    setGenerating(true)
    try {
      const res = await fetch('/api/generate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ topic: topic.trim(), platform, archetype }),
      })
      const data = await res.json()

      for (let i = 0; i < ALL_STAGES.length; i++) {
        const stage = ALL_STAGES[i]
        const content = data[stage]
        if (!content) continue
        const existing = blocks[stage]
        if (existing) {
          await supabase.from('blocks').update({ notes: content, status: 'done' }).eq('id', existing.id)
        } else {
          await supabase.from('blocks').insert({
            workflow_id: id,
            type: stage,
            title: STAGE_LABELS[stage],
            notes: content,
            status: 'done',
            order_index: i,
          })
        }
      }

      const { data: blks } = await supabase.from('blocks').select('*').eq('workflow_id', id).order('order_index')
      if (blks) {
        const map: Record<BlockType, Block | null> = { hook: null, script: null, shoot: null, edit: null, publish: null }
        blks.forEach((b) => { map[b.type as BlockType] = b })
        setBlocks(map)
      }
    } catch (err) {
      console.error('Generate error:', err)
    } finally {
      setGenerating(false)
    }
  }

  const doneCount = ALL_STAGES.filter((s) => blocks[s]?.status === 'done').length
  const progress = Math.round((doneCount / 5) * 100)

  return (
    <div className="min-h-screen bg-[#0f0f0f] text-white px-4 py-8 max-w-3xl mx-auto">
      {toast && <Toast message={toast.message} type={toast.type} onClose={() => setToast(null)} />}

      <button onClick={() => navigate('/')} className="text-[#6b7280] hover:text-white text-sm mb-6 flex items-center gap-1 transition-colors">
        ← Back
      </button>

      {/* Export */}
      <div className="relative flex items-center gap-3 mt-3">
        <button
          onClick={() => setIsExportOpen(true)}
          className="text-sm font-medium text-white mb-1 bg-[#7c3aed] hover:bg-[#6d28d9] rounded-lg px-3 py-1"
        >
          Export
        </button>
        {isExportOpen && (
          <div className="absolute top-8 left-0 z-50 bg-[#1a1a1a] border border-[#2a2a2a] shadow-lg rounded-lg p-3 w-48">
            <button
              onClick={() => handleExportOption('md')}
              className="block w-full text-left text-sm text-white hover:text-[#a78bfa] py-1.5 px-2 rounded hover:bg-[#2a2a2a]"
            >
              Export as Markdown
            </button>
            <button
              onClick={() => handleExportOption('pdf')}
              className="block w-full text-left text-sm text-white hover:text-[#a78bfa] py-1.5 px-2 rounded hover:bg-[#2a2a2a]"
            >
              Export as PDF
            </button>
            <button
              onClick={() => setIsExportOpen(false)}
              className="mt-2 w-full text-left text-xs text-[#6b7280] hover:text-white px-2 py-1"
            >
              Cancel
            </button>
          </div>
        )}
      </div>

      {/* Title + Progress */}
      <div className="mb-8">
        {editingTitle ? (
          <input
            value={workflowName}
            onChange={(e) => setWorkflowName(e.target.value)}
            onBlur={handleTitleSave}
            onKeyDown={(e) => { if (e.key === 'Enter') handleTitleSave() }}
            className="text-2xl font-bold text-white mb-1 bg-transparent border-b border-[#7c3aed] outline-none w-full max-w-xs"
            autoFocus
          />
        ) : (
          <h1 className="text-2xl font-bold text-white mb-1 cursor-pointer" onClick={() => setEditingTitle(true)}>
            {workflowName}
          </h1>
        )}
        <div className="flex items-center gap-3 mt-3">
          <div className="flex-1 h-1.5 bg-[#2a2a2a] rounded-full overflow-hidden">
            <div className="h-full bg-[#7c3aed] rounded-full transition-all duration-500" style={{ width: `${progress}%` }} />
          </div>
          <span className="text-[#6b7280] text-xs">{progress}% complete</span>
        </div>
      </div>

      {/* Platform + Generate */}
      <div className="mb-8 space-y-4">
  {/* Archetype Selector */}
  <div>
    <p className="text-xs text-[#6b7280] mb-2 font-medium uppercase tracking-widest">Content Archetype</p>
    <div className="flex gap-2 overflow-x-auto pb-2 scrollbar-hide">
      {ARCHETYPES.map((a) => (
        <button
          key={a.key}
          onClick={() => setArchetype(a.key)}
          className={`flex-shrink-0 text-left rounded-xl border px-3 py-2.5 w-36 transition-all ${
            archetype === a.key
              ? 'border-[#7c3aed] bg-[#7c3aed]/10'
              : 'border-[#2a2a2a] bg-[#1a1a1a] hover:border-[#3a3a3a]'
          }`}
        >
          <div className="text-lg mb-1">{a.emoji}</div>
          <div className="text-white text-xs font-semibold leading-tight">{a.label}</div>
          <div className="text-[#6b7280] text-[10px] mt-0.5 leading-tight line-clamp-2">{a.tagline}</div>
        </button>
      ))}
    </div>
    {/* Selected archetype preview */}
    {(() => {
      const selected = ARCHETYPES.find(a => a.key === archetype)
      if (!selected) return null
      return (
        <div className="mt-2 bg-[#1a1a1a] border border-[#2a2a2a] rounded-lg px-3 py-2 flex flex-wrap gap-x-4 gap-y-1">
          {selected.youllGet.map((item, i) => (
            <span key={i} className="text-[10px] text-[#a78bfa]">✦ {item}</span>
          ))}
        </div>
      )
    })()}
  </div>

  {/* Platform + Topic + Generate */}
  <div className="flex gap-3 flex-wrap">
    <div className="flex gap-2">
      <button onClick={() => setPlatform('instagram')} className={`text-xs px-4 py-2 rounded-lg transition-colors ${platform === 'instagram' ? 'bg-[#7c3aed] text-white' : 'bg-[#1a1a1a] text-[#6b7280] border border-[#2a2a2a]'}`}>Instagram Reels</button>
      <button onClick={() => setPlatform('youtube')} className={`text-xs px-4 py-2 rounded-lg transition-colors ${platform === 'youtube' ? 'bg-[#7c3aed] text-white' : 'bg-[#1a1a1a] text-[#6b7280] border border-[#2a2a2a]'}`}>YouTube Shorts</button>
      <button onClick={() => setPlatform('linkedin')} className={`text-xs px-4 py-2 rounded-lg transition-colors ${platform === 'linkedin' ? 'bg-[#7c3aed] text-white' : 'bg-[#1a1a1a] text-[#6b7280] border border-[#2a2a2a]'}`}>LinkedIn</button>
    </div>
    <input
      type="text"
      placeholder="e.g. 5 habits that changed my morning routine"
      value={topic}
      onChange={(e) => setTopic(e.target.value)}
      onKeyDown={(e) => e.key === 'Enter' && !generating && handleGenerate()}
      className="flex-1 bg-[#1a1a1a] border border-[#2a2a2a] text-white rounded-lg px-4 py-3 text-sm focus:outline-none focus:border-[#7c3aed] placeholder-[#6b7280]"
    />
    <button onClick={handleGenerate} disabled={generating || !topic.trim()} className="bg-[#7c3aed] hover:bg-[#6d28d9] disabled:opacity-50 text-white px-5 py-3 rounded-lg text-sm font-semibold transition-colors whitespace-nowrap">
      {generating ? 'Generating...' : 'Generate All'}
    </button>
  </div>
</div>

      {/* Stages */}
      <div className="space-y-3">
        {ALL_STAGES.map((stage) => {
          const block = blocks[stage]
          const meta = BLOCK_META[stage]
          return (
            <div key={stage}>
              {block ? (
                <BlockCard
                  block={block}
                  type={stage}
                  label={STAGE_LABELS[stage]}
                  icon={STAGE_ICONS[stage]}
                  meta={meta}
                  generating={generating}
                  workflowId={id!}
                  topic={topic}
                  isPro={isPro}
                  onUpdate={(updated) => setBlocks((prev) => ({ ...prev, [stage]: updated }))}
                />
              ) : (
                <div className="border border-[#2a2a2a] rounded-xl p-5 flex items-center gap-3 bg-[#1a1a1a]/30">
                  <span className="text-lg">{STAGE_ICONS[stage]}</span>
                  <div className="flex-1">
                    <p className="text-white font-medium text-sm">{STAGE_LABELS[stage]}</p>
                    {generating ? (
                      <div className="mt-2 space-y-1.5">
                        <div className="h-2 bg-[#2a2a2a] rounded animate-pulse w-3/4" />
                        <div className="h-2 bg-[#2a2a2a] rounded animate-pulse w-1/2" />
                      </div>
                    ) : (
                      <p className="text-[#6b7280] text-xs mt-0.5">Enter a topic and hit Generate All</p>
                    )}
                  </div>
                </div>
              )}
            </div>
          )
        })}
      </div>
    </div>
  )
}