import { useEffect, useState, useRef } from 'react'
import { useAuth } from '../hooks/useAuth'
import Toast from '../components/Toast'
import { useParams, useNavigate } from 'react-router-dom'
import { supabase } from '../lib/supabase'
import type { Block, BlockType } from '../lib/supabase'
import { BLOCK_META } from '../lib/supabase'
import BlockCard from '../components/BlockCard'
import WaitlistModal from '../components/WaitlistModal'
import { Download } from 'lucide-react'

const PRO_STAGES: BlockType[] = ['shoot', 'edit', 'publish']
const ALL_STAGES: BlockType[] = ['hook', 'script', 'shoot', 'edit', 'publish']

const STAGE_LABELS: Record<BlockType, string> = {
  hook: 'Hook',
  script: 'Script',
  shoot: 'Shoot Plan',
  edit: 'Edit Notes',
  publish: 'Publish Strategy',
}

const STAGE_ICONS: Record<BlockType, string> = {
  hook: '🎣',
  script: '📝',
  shoot: '🎬',
  edit: '✂️',
  publish: '🚀',
}

export default function WorkflowPage() {
  const { id } = useParams<{ id: string }>()
  const navigate = useNavigate()

  const [workflowName, setWorkflowName] = useState('')
  const [editingTitle, setEditingTitle] = useState(false)
  const [blocks, setBlocks] = useState<Record<BlockType, Block | null>>({
    hook: null, script: null, shoot: null, edit: null, publish: null,
  })
  const [topic, setTopic] = useState('')
  const [platform, setPlatform] = useState<'instagram'|'youtube'|'linkedin'>('instagram')
  const [toast, setToast] = useState<{message:string,type:'success'|'error'}|null>(null)
  const [generating, setGenerating] = useState(false)
  const [showWaitlist, setShowWaitlist] = useState(false)
  const [lockedStageClicked, setLockedStageClicked] = useState<BlockType>('shoot')

  const { user } = useAuth()
  const isPro = user?.user_metadata?.is_pro === true || localStorage.getItem('cre8flow_pro') === 'true'

  const [isExportOpen, setIsExportOpen] = useState(false);
  const [exportType, setExportType] = useState('md');

  const handleExport = () => {
    setIsExportOpen(true);
  };

  const handleExportOption = (type: 'md' | 'pdf') => {
    setExportType(type);
    setIsExportOpen(false);
    if (type === 'md') {
      handleMarkdownExport();
    } else {
      handlePDFAExport();
    }
  };

  const generateMarkdown = () => {
    let content = `# ${workflowName}\nGenerated by Cre8Flow | ${new Date().toISOString().slice(0,10)}\n\n`;

    const blockOrder = ['hook', 'script', 'shoot', 'edit', 'publish'];
    blockOrder.forEach(type => {
      const block = blocks[type];
      if (!block) return;
      content += `## ${block.title}\n`;
      const contentToUse = block.ai_content || block.notes;
      if (contentToUse) {
        content += `${contentToUse}\n---\n`;
      }
    });

    return content;
  };

  const handleMarkdownExport = () => {
    const content = generateMarkdown();
    const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${workflowName.replace(/\s+/g, '-')}-cre8flow.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handlePDFAExport = () => {
    document.body.classList.add('printing');
    window.print();
    setTimeout(() => {
      document.body.classList.remove('printing');
    }, 500);
  };

  const handleTitleSave = async () => {
    if (!id) return
    try {
      await supabase.from('workflows').update({ name: workflowName }).eq('id', id)
      setEditingTitle(false)
      showToast('Workflow name saved', 'success')
    } catch (e) {
      console.error(e)
      showToast('Failed to save workflow name', 'error')
    }
  }

  useEffect(() => {
    if (!id) return
    const load = async () => {
      const { data: wf } = await supabase.from('workflows').select('*').eq('id', id).single()
      if (wf) setWorkflowName(wf.name)

      const { data: blks } = await supabase.from('blocks').select('*').eq('workflow_id', id).order('order_index')
      if (blks) {
        const map: Record<BlockType, Block | null> = { hook: null, script: null, shoot: null, edit: null, publish: null }
        blks.forEach((b) => { map[b.type as BlockType] = b })
        setBlocks(map)
      }
    }
    load()
  }, [id])

  const handleGenerate = async () => {
    if (!topic.trim()) return
    setGenerating(true)
    try {
      const res = await fetch('/api/generate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ topic: topic.trim(), isPro, platform }),
      })
      const data = await res.json()
      const stagesToSave = isPro ? ALL_STAGES : (['hook', 'script'] as BlockType[])
      for (let i = 0; i < stagesToSave.length; i++) {
        const stage = stagesToSave[i]
        const content = data[stage]
        if (!content) continue
        const existing = blocks[stage]
        if (existing) {
          await supabase.from('blocks').update({ notes: content, status: 'done' }).eq('id', existing.id)
        } else {
          await supabase.from('blocks').insert({
            workflow_id: id,
            type: stage,
            title: STAGE_LABELS[stage],
            notes: content,
            status: 'done',
            order_index: i,
          })
        }
      }
      const { data: blks } = await supabase.from('blocks').select('*').eq('workflow_id', id).order('order_index')
      if (blks) {
        const map: Record<BlockType, Block | null> = { hook: null, script: null, shoot: null, edit: null, publish: null }
        blks.forEach((b) => { map[b.type as BlockType] = b })
        setBlocks(map)
      }
    } catch (err) {
      console.error('Generate error:', err)
    } finally {
      setGenerating(false)
    }
  }

  const handleLockedClick = (stage: BlockType) => {
    setLockedStageClicked(stage)
    setShowWaitlist(true)
  }

  const doneCount = ALL_STAGES.filter((s) => blocks[s]?.status === 'done').length
  const progress = Math.round((doneCount / 5) * 100)

    return (
    <div className="min-h-screen bg-[#0f0f0f] text-white px-4 py-8 max-w-3xl mx-auto">
      {showWaitlist && (
        <WaitlistModal stageName={STAGE_LABELS[lockedStageClicked]} onClose={() => setShowWaitlist(false)} />
      )}
      {toast && <Toast message={toast.message} type={toast.type} onClose={() => setToast(null)} />}
      <button onClick={() => navigate('/')} className="text-[#6b7280] hover:text-white text-sm mb-6 flex items-center gap-1 transition-colors">
        ← Back
      </button>

      {/* Export button added here */}
      <div className="flex items-center gap-3 mt-3">
        <button
          onClick={handleExport}
          className="text-sm font-medium text-white mb-1 bg-[#7c3aed] hover:bg-[#6d28d9] rounded-lg px-3 py-1"
        >
          <svg className="w-4 h-4" fill="none" stroke="white" stroke-width="2" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
          </svg>
          Export
        </button>
      </div>

      {isExportOpen && (
        <div className="absolute z-60 bg-white shadow-lg rounded-lg p-2 w-full">
          <div className="flex space-x-4">
            <button onClick={() => handleExportOption('md')}>Export as Markdown</button>
            <button onClick={() => handleExportOption('pdf')}>Export as PDF</button>
          </div>
          <button
            onClick={() => handleExport()}
            className="mt-2 bg-[#7c3aed] hover:bg-[#6d28d9] rounded-lg px-3 py-1"
          >
            Cancel
          </button>
        </div>
      )}
      <div className="mb-8">
        {editingTitle ? (
          <input
            value={workflowName}
            onChange={(e) => setWorkflowName(e.target.value)}
            onBlur={handleTitleSave}
            onKeyDown={(e) => { if (e.key === 'Enter') handleTitleSave() }}
            className="text-2xl font-bold text-white mb-1 bg-transparent border-b border-[#7c3aed] outline-none w-full max-w-xs"
            autoFocus
          />
        ) : (
          <h1 className="text-2xl font-bold text-white mb-1 cursor-pointer" onClick={() => setEditingTitle(true)}>
            {workflowName}
          </h1>
        )}
        <div className="flex items-center gap-3 mt-3">
          <div className="flex-1 h-1.5 bg-[#2a2a2a] rounded-full overflow-hidden">
            <div className="h-full bg-[#7c3aed] rounded-full transition-all duration-500" style={{ width: `${progress}%` }} />
          </div>
          <span className="text-[#6b7280] text-xs">{progress}% complete</span>
        </div>
        {!isPro && (
          <div className="mt-3 flex items-center gap-2 bg-[#7c3aed]/10 border border-[#7c3aed]/20 rounded-lg px-4 py-2.5">
            <span className="text-[#a78bfa] text-xs">🔒 Free plan: Hook + Script only.</span>
            <button onClick={() => { setLockedStageClicked('shoot'); setShowWaitlist(true) }} className="text-[#7c3aed] text-xs font-semibold hover:underline ml-auto">
              Upgrade to Pro →
            </button>
          </div>
        )}
      </div>
      <div className="flex gap-3 mb-8">
        <div className="flex gap-2 mb-2">
          <button onClick={() => setPlatform('instagram')} className={`text-xs px-4 py-2 rounded-lg transition-colors ${platform === 'instagram' ? 'bg-[#7c3aed] text-white border-[#7c3aed]' : 'bg-[#1a1a1a] text-[#6b7280] border border-[#2a2a2a]'}`}>Instagram Reels</button>
          <button onClick={() => setPlatform('youtube')} className={`text-xs px-4 py-2 rounded-lg transition-colors ${platform === 'youtube' ? 'bg-[#7c3aed] text-white border-[#7c3aed]' : 'bg-[#1a1a1a] text-[#6b7280] border border-[#2a2a2a]'}`}>YouTube Shorts</button>
          <button onClick={() => setPlatform('linkedin')} className={`text-xs px-4 py-2 rounded-lg transition-colors ${platform === 'linkedin' ? 'bg-[#7c3aed] text-white border-[#7c3aed]' : 'bg-[#1a1a1a] text-[#6b7280] border border-[#2a2a2a]'}`}>LinkedIn</button>
        </div>
        <input
          type="text"
          placeholder="e.g. 5 habits that changed my morning routine"
          value={topic}
          onChange={(e) => setTopic(e.target.value)}
          onKeyDown={(e) => e.key === 'Enter' && !generating && handleGenerate()}
          className="flex-1 bg-[#1a1a1a] border border-[#2a2a2a] text-white rounded-lg px-4 py-3 text-sm focus:outline-none focus:border-[#7c3aed] placeholder-[#6b7280]"
        />
        <button onClick={handleGenerate} disabled={generating || !topic.trim()} className="bg-[#7c3aed] hover:bg-[#6d28d9] disabled:opacity-50 text-white px-5 py-3 rounded-lg text-sm font-semibold transition-colors whitespace-nowrap">
          {generating ? 'Generating...' : 'Generate All'}
        </button>
      </div>
      <div className="space-y-3">
        {ALL_STAGES.map((stage) => {
          const isLocked = !isPro && PRO_STAGES.includes(stage)
          const block = blocks[stage]
          const meta = BLOCK_META[stage]
          if (isLocked) {
            return (
              <div key={stage} className="border border-[#2a2a2a] rounded-xl p-5 flex items-center justify-between bg-[#1a1a1a]/50">
                <div className="flex items-center gap-3">
                  <span className="text-lg">{STAGE_ICONS[stage]}</span>
                  <div>
                    <p className="text-[#6b7280] font-medium text-sm">{STAGE_LABELS[stage]}</p>
                    <p className="text-[#6b7280]/60 text-xs mt-0.5">Pro feature</p>
                  </div>
                </div>
                <button onClick={() => handleLockedClick(stage)} className="flex items-center gap-1.5 bg-[#7c3aed]/10 hover:bg-[#7c3aed]/20 border border-[#7c3aed]/30 text-[#a78bfa] text-xs font-semibold px-4 py-2 rounded-lg transition-colors">
                  🔒 Unlock
                </button>
              </div>
            )
          }
          return (
            <div key={stage}>
              {block ? (
                <BlockCard
                  block={block}
                  type={stage}
                  label={STAGE_LABELS[stage]}
                  icon={STAGE_ICONS[stage]}
                  meta={meta}
                  generating={generating}
                  workflowId={id!}
                  topic={topic}
                  isPro={isPro}
                  onUpdate={(updated) => setBlocks((prev) => ({ ...prev, [stage]: updated }))}
                />
              ) : (
                <div className="border border-[#2a2a2a] rounded-xl p-5 flex items-center gap-3 bg-[#1a1a1a]/30">
                  <span className="text-lg">{STAGE_ICONS[stage]}</span>
                  <div className="flex-1">
                    <p className="text-white font-medium text-sm">{STAGE_LABELS[stage]}</p>
                    {generating ? (
                      <div className="mt-2 space-y-1.5">
                        <div className="h-2 bg-[#2a2a2a] rounded animate-pulse w-3/4" />
                        <div className="h-2 bg-[#2a2a2a] rounded animate-pulse w-1/2" />
                      </div>
                    ) : (
                      <p className="text-[#6b7280] text-xs mt-0.5">Enter a topic and hit Generate All</p>
                    )}
                  </div>
                </div>
              )}
            </div>
          )
        })}
      </div>
    </div>
  )
}
