// ─── VIDEO TYPES ────────────────────────────────────────────────────────────

export const VIDEO_TYPES = [
  {
    id: 'talking_head',
    label: 'Talking Head / Voiceover',
    description: 'Face or voice-led content. Script drives the narrative.',
    hookStyle: 'verbal',
    scriptStyle: 'spoken_script',
  },
  {
    id: 'music_driven',
    label: 'Music-Driven / Cinematic',
    description: 'No dialogue. Music + visuals tell the story. Beat-synced editing.',
    hookStyle: 'visual',
    scriptStyle: 'visual_narrative',
  },
  {
    id: 'text_story',
    label: 'Text-on-Screen Story',
    description: 'Text overlays carry the narrative. Minimal or no voiceover.',
    hookStyle: 'text_visual',
    scriptStyle: 'text_overlay_script',
  },
]

export const HOOK_FORMULAS = [
  {
    name: 'The Brutal Truth',
    type: 'verbal',
    pattern: 'Nobody tells you [uncomfortable truth about topic]. Here\'s what actually happens.',
    example: 'Nobody tells you that 90% of productivity advice makes you less productive.',
    bestFor: 'self-improvement, business, fitness',
  },
  {
    name: 'The Curiosity Gap',
    type: 'verbal',
    pattern: 'The reason [common thing] doesn\'t work for you has nothing to do with [obvious assumption].',
    example: 'The reason you can\'t wake up early has nothing to do with discipline.',
    bestFor: 'lifestyle, habits, mindset',
  },
  {
    name: 'The Counterintuitive Claim',
    type: 'verbal',
    pattern: 'Doing [unexpected thing] every day completely changed [result].',
    example: 'Doing absolutely nothing for 10 minutes every morning changed my focus.',
    bestFor: 'productivity, wellness, personal growth',
  },
  {
    name: 'The Specific Number',
    type: 'verbal',
    pattern: '[Exact number] [things] that [strong outcome] — most people only know [lower number].',
    example: '7 phrases that got me a 40% raise — most people only know 2.',
    bestFor: 'career, money, skills',
  },
  {
    name: 'The Story Drop',
    type: 'verbal',
    pattern: '[Specific moment] — I had no idea this would [dramatic outcome].',
    example: 'I was sitting in a coffee shop at 11pm, broke — I had no idea this moment would change everything.',
    bestFor: 'personal stories, transformation content',
  },
  {
    name: 'The Motion Tease',
    type: 'visual',
    pattern: 'Open on a visually stunning or mysterious shot mid-motion. No context given. Let the music drop answer the question.',
    example: 'Extreme close-up of hands writing, rain on window, city lights blurred — cut to black — music hits.',
    bestFor: 'aesthetic montage, cinematic, DARKROOM-style',
  },
  {
    name: 'The Before-Beat Freeze',
    type: 'visual',
    pattern: 'One still, high-contrast frame held for 1-2 seconds before the beat drops. Builds anticipation.',
    example: 'Silhouette against light, completely still. 1.5 seconds. Then cut on the drop.',
    bestFor: 'K-editorial, fashion, dark/moody',
  },
  {
    name: 'The Slow Pull',
    type: 'visual',
    pattern: 'Open in 0.5x slow motion on an ordinary moment made cinematic. Let the viewer feel the texture of the scene.',
    example: 'Slow pour of coffee, slow footstep on wet pavement, slow turn of pages — mundane made beautiful.',
    bestFor: 'warm film aesthetic, day-in-life, lifestyle montage',
  },
  {
    name: 'The Text Opener',
    type: 'text_visual',
    pattern: 'Single line of text appears first — before any visuals. White on black or grain overlay. One sentence that recontextualizes everything that follows.',
    example: '"this is what running away looks like" — then the travel footage begins.',
    bestFor: 'text-story, POV narrative, abstract storytelling',
  },
  {
    name: 'The System Boot',
    type: 'text_visual',
    pattern: 'Monospace font text types onto screen like a terminal command. Sets a cold, intentional mood.',
    example: 'LOADING: [topic] ... 100% — cut to content.',
    bestFor: 'SYSTEM ONLINE aesthetic, abstract, editorial',
  },
]

export const SCRIPT_STRUCTURES = [
  {
    name: 'Problem-Agitate-Solve (PAS)',
    type: 'verbal',
    pattern: 'Open with the problem → make the audience feel the pain → deliver the solution clearly',
    breakdown: [
      'Hook: state the problem in one sentence',
      'Agitate: 2-3 sentences on why this problem is worse than people think',
      'Solve: clear, actionable answer in 3-5 steps or one insight',
      'CTA: one specific action to take right now',
    ],
    idealLength: '45-60 seconds',
    bestFor: 'educational, how-to, self-improvement',
  },
  {
    name: 'Before-After-Bridge (BAB)',
    type: 'verbal',
    pattern: 'Paint the before state → show the after state → reveal the bridge',
    breakdown: [
      'Before: the painful current reality',
      'After: the aspirational transformed state',
      'Bridge: the exact method connecting them',
      'Deliver the bridge in 3-4 clear points',
    ],
    idealLength: '30-50 seconds',
    bestFor: 'transformation stories, product demos, lifestyle content',
  },
  {
    name: 'The Myth-Buster',
    type: 'verbal',
    pattern: 'State a widely believed thing → challenge it → replace with a better belief',
    breakdown: [
      'Myth: state the common belief',
      'Challenge: why it is incomplete or wrong',
      'Evidence: experience, data, or logic',
      'Better belief: the upgraded version',
    ],
    idealLength: '40-60 seconds',
    bestFor: 'contrarian takes, thought leadership, niche expertise',
  },
  {
    name: 'The Tutorial Sprint',
    type: 'verbal',
    pattern: 'Promise a result → show exact steps → confirm the result',
    breakdown: [
      'Promise: I will show you exactly how to do X',
      'Steps: clean, fast, no fluff — max 5 steps',
      'Result: show or confirm the outcome',
      'Bonus: one thing most tutorials miss',
    ],
    idealLength: '30-60 seconds',
    bestFor: 'tutorials, software, cooking, technique',
  },
]

export const VISUAL_NARRATIVE_STRUCTURES = [
  {
    name: 'The Emotional Arc',
    type: 'music_driven',
    pattern: 'Build from quiet/slow visuals → peak at the music most intense moment → end on something still and unresolved.',
    acts: [
      'Act 1 (intro): Slow, textured shots. Grain. Small details. Establish mood.',
      'Act 2 (build): Movement enters — walking, panning, environmental energy picks up.',
      'Act 3 (drop/peak): Fastest cuts, strongest visuals, most contrast.',
      'Act 4 (outro): Return to stillness. One final frame held 2-3 seconds after music fades.',
    ],
    bestFor: 'DARKROOM-style, cinematic montage, emotional storytelling',
    musicSync: 'Verse = slow/medium. Pre-chorus = build tension. Chorus = peak energy. Bridge = unexpected stillness.',
  },
  {
    name: 'The Day Log',
    type: 'music_driven',
    pattern: 'Chronological moments from a day or period. No narration. The sequence of shots creates the story.',
    acts: [
      'Morning: establish the space, light quality, routine details',
      'Transition: movement out — leaving, commuting, arriving',
      'Peak moment: the reason the day was worth filming',
      'Return: evening light, winding down, reflection shot',
    ],
    bestFor: 'day-in-life, FLIGHT LOG aesthetic, travel, personal archives',
    musicSync: 'Match music tempo to time of day energy — slow for morning/night, faster for midday.',
  },
  {
    name: 'The Concept Film',
    type: 'music_driven',
    pattern: 'Abstract idea translated into visual metaphors. No literal representation. Viewer constructs meaning.',
    acts: [
      'Establish the metaphor: one recurring visual motif (water, fire, mirrors, doors)',
      'Develop tension: the motif appears in different contexts',
      'Subvert: show the motif broken, changed, or inverted',
      'Resolution or non-resolution: end ambiguously',
    ],
    bestFor: 'CLASSIFIED / BLACK BOX aesthetic, abstract, artistic expression',
    musicSync: 'Choose music with emotional arc. The music IS the script.',
  },
  {
    name: 'The Identity Portrait',
    type: 'music_driven',
    pattern: 'A person or place as subject. No dialogue. The edit reveals character through selected moments.',
    acts: [
      'Exterior: how they appear to the world',
      'Detail: the small things that reveal depth — hands, objects, textures',
      'In motion: doing something they love or know deeply',
      'Still: one final frame that holds the whole portrait',
    ],
    bestFor: 'fashion, K-editorial, character studies, idol trainee aesthetic',
    musicSync: 'Match music to subject energy. K-pop instrumentals or lo-fi city pop for editorial.',
  },
  {
    name: 'The Transition Film',
    type: 'music_driven',
    pattern: 'Transitions ARE the content. Each cut is a creative match — by color, shape, movement, or theme.',
    acts: [
      'Set the base: first 3-4 cuts establish the transition style',
      'Escalate: transitions get more complex toward the drop',
      'Peak: most impressive transition lands on the biggest beat',
      'Cool down: last 2-3 cuts slow back, final frame holds',
    ],
    bestFor: 'trend-driven content, outfit showcases, travel reels',
    musicSync: 'Every transition must land on a beat. Map cuts to song before filming.',
  },
  {
    name: 'The Shayari Film',
    type: 'text_story',
    pattern: 'Urdu/Hindi poetic text overlaid on cinematic visuals. Text IS the narrative. Visuals serve the words.',
    acts: [
      'First frame: single word or half-line on black or textured background',
      'Develop: each frame reveals the next line as visuals match the emotion',
      'Turn: the shayari emotional pivot happens at video midpoint',
      'Khatam: last line holds on screen 3-4 seconds. Music fades. Silence.',
    ],
    bestFor: 'Urdu poetry content, emotional reels, literary aesthetic',
    musicSync: 'Instrumental ghazal, sad lo-fi, or ambient drone. Music at 30-40% — words are primary.',
  },
]

export const SHOT_TYPES = [
  {
    name: 'Hero Shot (Wide Establishing)',
    type: 'universal',
    use: 'Opens the video, sets location and mood',
    specs: '6-10 feet from subject. Include full environment.',
    tip: 'Film this last — you will know the mood by then.',
  },
  {
    name: 'Talking Head (Medium)',
    type: 'talking_head',
    use: 'Main delivery for scripts and voiceover content',
    specs: 'Frame mid-chest to 3 inches above head. Eyes at upper third.',
    tip: 'Look slightly above lens for authority. Into lens for intimacy.',
  },
  {
    name: 'Extreme Close-Up (Texture Shot)',
    type: 'cinematic',
    use: 'Grain, skin, fabric, objects — makes the mundane cinematic',
    specs: 'As close as lens allows. Fill the entire frame with one texture.',
    tip: 'Unfocus slightly for an ethereal feel. Works beautifully in slow motion.',
  },
  {
    name: 'Silhouette Shot',
    type: 'cinematic',
    use: 'Mystery, identity, aesthetics — faceless storytelling',
    specs: 'Subject between camera and light source. Expose for background not subject.',
    tip: 'Window light, golden hour, or streetlights. The light source shape matters.',
  },
  {
    name: 'Slow Motion (0.5x - 0.3x)',
    type: 'cinematic',
    use: 'Makes ordinary moments feel heavy, intentional, cinematic',
    specs: 'Film at 60fps or 120fps. Apply 0.5x in edit.',
    tip: 'The mundane in slow motion is always beautiful. Coffee poured. Rain on glass. Hair falling.',
  },
  {
    name: 'B-Roll (Cutaway)',
    type: 'universal',
    use: 'Supports narrative — shows the thing being talked about or felt',
    specs: 'Film 4-5x more B-roll than you need. Each clip: 3-8 seconds.',
    tip: 'Film B-roll in 3 movements per subject: static, pan, push-in.',
  },
  {
    name: 'Overhead (Flat Lay)',
    type: 'cinematic',
    use: 'Objects, workspaces, aesthetic arrangements — editorial fashion influence',
    specs: 'Camera directly above subject. Everything arranged intentionally.',
    tip: 'Negative space is as important as the subject. Do not fill every corner.',
  },
  {
    name: 'POV (First Person)',
    type: 'narrative',
    use: 'Immersive, faceless storytelling. Viewer becomes the subject.',
    specs: 'Camera at eye level, slightly unstabilized for authenticity.',
    tip: 'What your hands do tells the story. Walking, writing, making something.',
  },
  {
    name: 'Reflection Shot',
    type: 'cinematic',
    use: 'Mirrors, puddles, glass — adds depth and metaphor',
    specs: 'Focus on the reflection, not the surface.',
    tip: 'Powerful for identity content — literally seeing yourself differently.',
  },
  {
    name: 'Natural Light Window Frame',
    type: 'cinematic',
    use: 'Warm, intimate, human — the K-drama lighting setup',
    specs: 'Subject beside window, light from the side. Camera perpendicular to window.',
    tip: 'Blue hour gives the most cinematic window light.',
  },
  {
    name: 'Urban Architecture Detail',
    type: 'cinematic',
    use: 'City texture, environment, FLIGHT LOG aesthetic',
    specs: 'Find geometric patterns, repeating shapes, interesting light on concrete or glass.',
    tip: 'Look up and down, not just forward. Best urban shots are ceiling and floor level.',
  },
]

export const EDIT_PATTERNS = [
  {
    name: 'Beat Drop Cut',
    type: 'music_driven',
    rule: 'The most impactful cut lands exactly on the beat drop. Everything before builds to it. Everything after releases from it.',
    timing: 'Map your song first. Mark the drop. Build your best shot around that cut.',
    vibe: 'High impact, satisfying, rewatchable',
    platforms: 'Instagram Reels, TikTok, YouTube Shorts',
  },
  {
    name: 'The DARKROOM Edit',
    type: 'aesthetic',
    rule: 'Grain at 70-80. Speed at 0.5x-0.7x on most shots. Hard cuts only — no smooth transitions. Cinema or Retro filter. Audio at 30-40% max. Monospace text if any.',
    timing: 'Cuts every 3-5 seconds. Let slow motion breathe. No rush.',
    vibe: 'Dark, heavy, intentional — analog photography meets digital',
    platforms: 'Instagram Reels, personal brand content',
  },
  {
    name: 'K-Editorial Cut',
    type: 'aesthetic',
    rule: 'Clean, cold color grade (slight blue/teal in shadows). Sharp cuts on beats. Fashion-forward framing — lots of negative space. Text minimal, sans-serif, lowercase.',
    timing: 'Medium pace — controlled energy.',
    vibe: 'High fashion, East Asian editorial, aspirational',
    platforms: 'Instagram, editorial content',
  },
  {
    name: 'Warm Film Edit',
    type: 'aesthetic',
    rule: 'Warm shadows (orange/brown tones). Slight overexposure. Film grain at 40-60. Soft cuts or match cuts. Natural sound design layered under music.',
    timing: 'Slower pace. Shots breathe. 4-7 seconds each.',
    vibe: 'Nostalgic, human, analog warmth',
    platforms: 'Instagram Reels, YouTube, personal archives',
  },
  {
    name: 'The Jump Cut Rhythm',
    type: 'talking_head',
    rule: 'Cut on every breath or pause. Remove all filler words. Zero dead air.',
    timing: 'Cuts every 1.5-3 seconds on talking head footage.',
    vibe: 'Fast-paced, no wasted time',
    platforms: 'YouTube Shorts, TikTok, Reels',
  },
  {
    name: 'The Match Cut',
    type: 'cinematic',
    rule: 'Cut between two visually similar shapes, movements, or colors. The transition feels inevitable, not forced.',
    timing: 'Use at emotional peaks or topic changes.',
    vibe: 'Cinematic, intentional, rewarding',
    platforms: 'All platforms',
  },
  {
    name: 'The Music-First Edit',
    type: 'music_driven',
    rule: 'Place music on timeline first. Find the drops, builds, transitions. Cut footage to match — never the reverse.',
    timing: 'Cuts land on beat hits, snare, chord changes.',
    vibe: 'Cohesive, musical, intentional',
    platforms: 'All music-driven content',
  },
  {
    name: 'The Still Frame Hold',
    type: 'cinematic',
    rule: 'Pause on a single frame for 1-3 seconds before or after the most important moment. Let the viewer sit in it.',
    timing: 'Before drop (anticipation) or after peak (resolution).',
    vibe: 'Heavy, poetic, makes viewers feel something',
    platforms: 'All — especially powerful for emotional content',
  },
  {
    name: 'Text-on-Screen Timing',
    type: 'text_story',
    rule: 'Text stays on screen exactly as long as it takes to read it aloud twice. Appears on a beat. Disappears on a beat.',
    timing: 'Short line: 2 seconds. Full sentence: 3.5 seconds. Poetic line: 4 seconds.',
    vibe: 'Clean, readable, intentional',
    platforms: 'All — essential for muted viewing',
  },
]

export const MUSIC_SYNC_PATTERNS = [
  {
    name: 'Verse-Chorus Architecture',
    pattern: 'Verse = slower establishing shots. Pre-chorus = energy builds, movement enters. Chorus = fastest cuts, most dynamic shots. Bridge = break the pattern intentionally.',
    tip: 'Map your entire song structure before importing a single clip.',
  },
  {
    name: 'Emotional Tempo Matching',
    pattern: 'Soft music → slow shots, minimal motion, breathing room. Intense music → faster cuts, more movement, tighter frames.',
    tip: 'Watch your edit with eyes closed first. If it feels right rhythmically, it will look right visually.',
  },
  {
    name: 'The Silence Drop',
    pattern: 'Cut all music for 0.5-1 second before a major beat drop. Pure silence. Then the drop hits. The contrast makes the moment enormous.',
    tip: 'Used by the best music video editors globally. Stolen directly from K-pop MVs.',
  },
  {
    name: 'Diegetic Sound Layer',
    pattern: 'Layer natural/ambient sound under music at 5-15% volume. Rain, city noise, wind, cafe sounds. Music stays primary but the world feels real.',
    tip: 'Even in fully music-driven video, ambient sound makes it feel grounded.',
  },
]

export const AESTHETIC_STYLES = [
  {
    name: 'DARKROOM',
    description: 'Analog photography metaphor. Dark, heavy, intentional.',
    colorGrade: 'Desaturated base. Crushed blacks. Slight green or magenta cast in shadows.',
    grain: '70-80 intensity. Fine grain. Applied after color grade.',
    speed: '0.5x-0.7x on most shots.',
    text: 'Monospace font. Lowercase. White on dark. Minimal words.',
    music: 'Dark ambient, slow electronic, lo-fi with weight.',
    avoid: 'Warm tones, bright sunlight, fast cuts, emoji in captions',
  },
  {
    name: 'K-Editorial',
    description: 'East Asian fashion editorial. Clean, cold, precise.',
    colorGrade: 'Cool shadows (blue/teal). Clean mids. Slightly muted highlights. High contrast.',
    grain: '20-40 intensity. Very fine or none.',
    speed: 'Mostly real-time. Slow motion used surgically.',
    text: 'Sans-serif. Lowercase. Minimal.',
    music: 'K-indie, city pop, clean electronic, minimal beats.',
    avoid: 'Warm heavy grain, shaky cam, text-heavy graphics',
  },
  {
    name: 'Warm Film',
    description: 'Analog film warmth. Golden hour memory. Human and nostalgic.',
    colorGrade: 'Warm shadows (orange/brown). Lifted blacks. Slight overexposure.',
    grain: '40-60 intensity. Coarser grain for analog feel.',
    speed: '0.8x-1x. Mostly real-time.',
    text: 'Serif or handwritten. Lowercase. Warm white or cream.',
    music: 'Lo-fi, acoustic, nostalgic indie, gentle electronic.',
    avoid: 'Cold color grades, sharp harsh cuts, clinical text',
  },
  {
    name: 'Abstract / Concept',
    description: 'Visual metaphor-driven. No literal representation. CLASSIFIED / BLACK BOX energy.',
    colorGrade: 'Whatever serves the concept. Monochrome, split toned, or inverted.',
    grain: 'Variable — used as expressive tool.',
    speed: 'Variable — slow and fast within same video for deliberate contrast.',
    text: 'Terminal-style, redacted boxes, glitch text, or none.',
    music: 'Experimental, ambient, anything that serves emotion not trend.',
    avoid: 'Literal interpretation, generic trending sounds, predictable structures',
  },
]

export const TRANSITION_TYPES = [
  {
    name: 'Hard Cut',
    difficulty: 'beginner',
    description: 'Direct cut between clips. The foundation of all editing.',
    bestWhen: 'Always. The hard cut is the default. Everything else is an exception.',
    tip: 'A perfectly timed hard cut on a beat is more powerful than any fancy transition.',
  },
  {
    name: 'Whip Pan',
    difficulty: 'beginner',
    description: 'Camera pans fast — motion blur — cuts to new scene in same motion blur.',
    bestWhen: 'Location changes, time jumps, energy transitions.',
    tip: 'Film a fast pan right at end of one clip and left at start of next. Match speed in edit.',
  },
  {
    name: 'Match Cut',
    difficulty: 'intermediate',
    description: 'Two clips with matching shapes, colors, or movements connected as one fluid motion.',
    bestWhen: 'Thematic connections, contrasts, transformations.',
    tip: 'Best match cuts feel like magic but are planned during shooting.',
  },
  {
    name: 'Smash Cut',
    difficulty: 'beginner',
    description: 'Jarring cut from calm to intense or intense to calm. The contrast IS the effect.',
    bestWhen: 'Before-after content, dramatic reveals.',
    tip: 'One side must be dramatically different for the smash cut to work.',
  },
  {
    name: 'Hand/Object Wipe',
    difficulty: 'intermediate',
    description: 'Object passes in front of camera to obscure frame — new scene revealed.',
    bestWhen: 'Outfit changes, location transitions, tutorial steps.',
    tip: 'Film the wipe object very close to lens. It should fill the entire frame at peak.',
  },
  {
    name: 'Colour Flash Cut',
    difficulty: 'intermediate',
    description: 'Single frame of white, black, or color between clips.',
    bestWhen: 'On hard beat hits. Major transitions. After a peak moment.',
    tip: '2-4 frames only. Too long and it becomes a mistake, not a technique.',
  },
]

export const PUBLISH_STRATEGIES = [
  {
    platform: 'Instagram Reels',
    bestTime: '8-10pm weekdays (IST). Consistency beats optimal timing.',
    captionFormula: 'Hook line → 2-3 lines of value → CTA → line break → hashtags',
    hashtagStrategy: '5-8 hashtags: 2 large (1M+), 3 medium (100K-500K), 2-3 niche (under 50K).',
    ctaFormulas: ['save this', 'share with someone who needs this', 'drop a checkmark if this hit', 'tell me your thoughts below'],
    coverFrame: 'High-contrast or text-hook frame. Avoid blurry or transitional frames.',
    audioTip: 'Trending audio at 50-70% under voice. Check Reels audio tab weekly.',
    aestheticNote: 'First frame = cover image on profile grid. Design it intentionally.',
  },
  {
    platform: 'YouTube Shorts',
    bestTime: '12-3pm and 6-9pm any day.',
    captionFormula: 'SEO title with keyword first → 1-2 line description with secondary keywords.',
    hashtagStrategy: '#Shorts mandatory. Add 2-3 topic hashtags max.',
    ctaFormulas: ['subscribe for more on this topic', 'watch the full video', 'comment for part 2'],
    coverFrame: 'Custom thumbnail — text overlay plus expressive frame performs best.',
    audioTip: 'Original audio performs better for search.',
    aestheticNote: 'YouTube Shorts favors content that drives watch-through. Hook in first 0.5 seconds.',
  },
  {
    platform: 'LinkedIn',
    bestTime: 'Tuesday-Thursday, 7-9am or 12-1pm.',
    captionFormula: 'Strong first line → personal insight in 3-5 short paragraphs → lesson → question',
    hashtagStrategy: '3-5 professional industry hashtags. No pop culture.',
    ctaFormulas: ['what is your experience with this', 'repost if this was useful', 'follow for weekly insights'],
    coverFrame: 'Professional, clean. Captions essential — most LinkedIn users scroll on mute.',
    audioTip: 'Assume no sound. Text overlays carry the narrative.',
    aestheticNote: 'LinkedIn rewards authenticity more than polish. Personal story beats perfect production.',
  },
  {
    platform: 'TikTok',
    bestTime: '6-10pm any day. Consistent daily posting beats sporadic quality.',
    captionFormula: 'Short hook under 100 chars → 2-3 relevant hashtags.',
    hashtagStrategy: '#fyp plus 2-3 niche hashtags. Irrelevant trending hashtags hurt performance.',
    ctaFormulas: ['stitch this with your version', 'duet this', 'follow for part 2 tomorrow'],
    coverFrame: 'Text hook frame as cover increases profile tap-through.',
    audioTip: 'Trending audio is the single biggest distribution lever on TikTok.',
    aestheticNote: 'TikTok rewards relatability and authenticity. High production can actually hurt.',
  },
]
