name: Cre8Flow Config
version: 1.0.0
schema: v1

models:
  - name: Groq Llama
    provider: openai
    model: llama-3.3-70b-versatile
    apiBase: https://api.groq.com/openai/v1
    apiKey: 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

context:
  - provider: code
  - provider: folder